import type { Visitor } from "./visitors";

function daysAgo(d: number, hour = 9, min = 0): string {
  const date = new Date();
  date.setDate(date.getDate() - d);
  date.setHours(hour, min, 0, 0);
  return date.toISOString();
}

export const MOCK_VISITORS: Visitor[] = [
  {
    id: "v_mock_001",
    name: "Brian Otieno",
    email: "brian.otieno@ku.ac.ke",
    phone: "+254 712 345 678",
    company: "Kenyatta University",
    host: "Vice Chancellor's Office",
    purpose: "Academic Collaboration",
    idType: "national-id",
    idNumber: "12345678",
    checkInTime: daysAgo(0, 8, 30),
    status: "checked-in",
    location: {
      lat: -0.7682,
      lng: 34.6048,
      accuracy: 12,
      distanceKm: 0.1,
      timestamp: daysAgo(0, 8, 30),
    },
  },
  {
    id: "v_mock_002",
    name: "David Ochieng",
    email: "d.ochieng@gmail.com",
    phone: "+254 733 456 789",
    company: "Ministry of Education",
    host: "Registrar (Academic Affairs)",
    purpose: "Audit / Inspection",
    idType: "national-id",
    idNumber: "98765432",
    checkInTime: daysAgo(0, 9, 15),
    checkOutTime: daysAgo(0, 10, 45),
    status: "checked-out",
    location: {
      lat: -0.7671,
      lng: 34.6059,
      accuracy: 8,
      distanceKm: 0.2,
      timestamp: daysAgo(0, 9, 15),
    },
  },
  {
    id: "v_mock_003",
    name: "Dr. Grace Akinyi",
    email: "gakinyi@cue.or.ke",
    phone: "+254 701 234 567",
    company: "Commission for University Education",
    host: "Deputy Vice Chancellor (ASA)",
    purpose: "Accreditation Review",
    idType: "passport",
    idNumber: "KE1234567",
    checkInTime: daysAgo(0, 10, 0),
    status: "checked-in",
    location: {
      lat: -0.7665,
      lng: 34.6042,
      accuracy: 15,
      distanceKm: 0.3,
      timestamp: daysAgo(0, 10, 0),
    },
  },
  {
    id: "v_mock_004",
    name: "James Kariuki",
    email: "jkariuki@speedydelivery.co.ke",
    phone: "+254 722 987 654",
    company: "Speedy Courier Services",
    host: "Main Reception & Information Desk",
    purpose: "Delivery",
    idType: "national-id",
    idNumber: "55566677",
    checkInTime: daysAgo(0, 11, 20),
    checkOutTime: daysAgo(0, 11, 35),
    status: "checked-out",
    location: {
      lat: -0.769,
      lng: 34.606,
      accuracy: 20,
      distanceKm: 0.4,
      timestamp: daysAgo(0, 11, 20),
    },
  },
  {
    id: "v_mock_005",
    name: "Eunice Kwamboka",
    email: "eunice.k@techkenya.co.ke",
    phone: "+254 799 876 543",
    company: "Kenya Power & Lighting",
    host: "Procurement & Supplies",
    purpose: "Support / Maintenance",
    idType: "national-id",
    idNumber: "44433322",
    checkInTime: daysAgo(1, 9, 0),
    checkOutTime: daysAgo(1, 17, 30),
    status: "checked-out",
  },
  {
    id: "v_mock_006",
    name: "Emmanuel Sila",
    email: "esila@kenet.or.ke",
    phone: "+254 788 654 321",
    company: "KENET",
    host: "ICT Directorate",
    purpose: "Support / Maintenance",
    idType: "drivers-license",
    idNumber: "DL-20249876",
    checkInTime: daysAgo(0, 13, 0),
    status: "checked-in",
    location: {
      lat: -0.7675,
      lng: 34.6053,
      accuracy: 5,
      distanceKm: 0.0,
      timestamp: daysAgo(0, 13, 0),
    },
  },
];
