import type { Visitor } from "./visitors";

function daysAgo(d: number, hour = 9, min = 0): string {
  const date = new Date();
  date.setDate(date.getDate() - d);
  date.setHours(hour, min, 0, 0);
  return date.toISOString();
}

export const MOCK_VISITORS: Visitor[] = [
  {
    id: "v_mock_001",
    name: "Amina Hassan",
    email: "amina.hassan@techcorp.com",
    phone: "+254 712 345 678",
    company: "TechCorp Ltd",
    host: "John Mwangi",
    purpose: "Business Meeting",
    idType: "national-id",
    idNumber: "12345678",
    checkInTime: daysAgo(0, 8, 30),
    status: "checked-in",
  },
  {
    id: "v_mock_002",
    name: "David Ochieng",
    email: "d.ochieng@gmail.com",
    phone: "+254 733 456 789",
    company: "Freelancer",
    host: "Sarah Kamau",
    purpose: "Interview",
    idType: "national-id",
    idNumber: "98765432",
    checkInTime: daysAgo(0, 9, 15),
    checkOutTime: daysAgo(0, 10, 45),
    status: "checked-out",
  },
  {
    id: "v_mock_003",
    name: "Fatima Al-Rashid",
    email: "fatima@partner.ae",
    phone: "+971 50 123 4567",
    company: "Gulf Partners",
    host: "Peter Ndung'u",
    purpose: "Partnership Discussion",
    idType: "passport",
    idNumber: "AE1234567",
    checkInTime: daysAgo(0, 10, 0),
    status: "checked-in",
  },
  {
    id: "v_mock_004",
    name: "James Kariuki",
    email: "jkariuki@delivery.co.ke",
    phone: "+254 722 987 654",
    company: "Swift Delivery",
    host: "Reception",
    purpose: "Package Delivery",
    idType: "national-id",
    idNumber: "55566677",
    checkInTime: daysAgo(0, 11, 20),
    checkOutTime: daysAgo(0, 11, 35),
    status: "checked-out",
  },
  {
    id: "v_mock_005",
    name: "Grace Wanjiku",
    email: "grace.wanjiku@audit.co.ke",
    phone: "+254 701 234 567",
    company: "Deloitte Kenya",
    host: "CFO Office",
    purpose: "Audit Visit",
    idType: "national-id",
    idNumber: "44433322",
    checkInTime: daysAgo(1, 9, 0),
    checkOutTime: daysAgo(1, 17, 30),
    status: "checked-out",
  },
  {
    id: "v_mock_006",
    name: "Mohamed Ibrahim",
    email: "m.ibrahim@consult.com",
    phone: "+254 799 876 543",
    company: "McKinsey & Co",
    host: "CEO Office",
    purpose: "Strategic Consultation",
    idType: "passport",
    idNumber: "KE9876543",
    checkInTime: daysAgo(1, 14, 0),
    checkOutTime: daysAgo(1, 16, 0),
    status: "checked-out",
  },
  {
    id: "v_mock_007",
    name: "Lucy Njoroge",
    email: "lucy@supplier.co.ke",
    phone: "+254 788 654 321",
    company: "Office Supplies KE",
    host: "Procurement",
    purpose: "Supplier Meeting",
    idType: "drivers-license",
    idNumber: "DL-20221234",
    checkInTime: daysAgo(2, 10, 30),
    checkOutTime: daysAgo(2, 12, 0),
    status: "checked-out",
  },
  {
    id: "v_mock_008",
    name: "Kevin Otieno",
    email: "kevin@startup.io",
    phone: "+254 711 222 333",
    company: "Nairobi Startup Hub",
    host: "John Mwangi",
    purpose: "Investment Pitch",
    idType: "national-id",
    idNumber: "77788899",
    checkInTime: daysAgo(0, 13, 0),
    status: "checked-in",
  },
];
